[alembic]
script_location = alembic
sqlalchemy.url = postgresql://jobuser:jobpassword@localhost:5432/ai_jobs_db

[loggers]
keys = root,sqlalchemy,alembic

[logger_alembic]
level = INFO
handlers =
qualname = alembic
